name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*"
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.yml"
      - .editorconfig
      - ".github/**"
      - .gitignore
      - .gitattributes
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.yml"
      - .editorconfig
      - ".github/**"
      - .gitignore
      - .gitattributes

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
          path: "."
          pattern: "*.sh"
      - run: ./build.sh --verbose
        name: Build
      - name: Commit build results to built branch
        if: success() && github.event_name != 'pull_request' && startsWith(github.ref, 'refs/heads/main')
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'giggio@users.noreply.github.com'
          git checkout built
          git merge -X theirs main
          git add dist -f
          git commit -m "Automated build"
          git push origin built
